package com.neutralplasma.virtusbot.settings

enum class SettingsList {
    WELCOME_MESSAGE_CHANNEL, // WHERE IS THE WELCOME MESSAGE SENT
    LOG_CHANNEL, // CHANNEL FOR LOGGING ERRORS AND THAT STUFF
    TICKET_CHANNEL, // CHANNEL WHERE YOU CAN CREATE TICKETS (CREATE CHANNEL WITH COMMAND)
    SUGGEST_CHANNEL, // CHANNEL FOR SUGGESTIONS (WHERE THEY GET SENT)
    SUPPORT_ROLE, // SUPPORT ROLE
    LEVEL_UP_CHANNEL, // CHANNEL WHERE LEVELUP MESSAGES GET SENT.
    OPEN_TICKET_CATEGORY, // CATEGOR OF ALL OPEN TICKETS
}